
### variables from .vscode/settings.json

###
# @name ClientCredentialsGrant
POST {{authUrl}}/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{client_id}}
&client_secret={{client_secret}}
&scope=Api


###
# NlSfbRoot
POST {{baseUrl}}/api/v1/NlSfb/Root HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"Languagecode": "nl-NL"
}

###
# NlSfbRoot
POST {{baseUrl}}/api/v1/NlSfb/Root HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"Languagecode": "nl-NL",
	"Include": {
		"Descriptions": true,
		"Translations": true
	}
}

###
# Details
POST {{baseUrl}}/api/v1/NlSfb/Details HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"Languagecode": "nl-NL",
	"Id": "05f3645d-ff65-4672-a92c-9b387852ed16",
	"Release": "Dynamic"
}

###
# Details
POST {{baseUrl}}/api/v1/NlSfb/Details HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"Languagecode": "nl-NL",
	"Id": "05f3645d-ff65-4672-a92c-9b387852ed16",
	"Release": "Dynamic",
	"Include": {
		"Descriptions": false,
		"Translations": false
	}
}

###
# NlSfbChildren
POST {{baseUrl}}/api/v1/NlSfb/Children HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"Languagecode": "nl-NL",
	"Id": "05f3645d-ff65-4672-a92c-9b387852ed16",
	"Release": "NL/SfB 2019"
}

###
# NlSfbChildren
POST {{baseUrl}}/api/v1/NlSfb/Children HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"Languagecode": "nl-NL",
	"Id": "962d75e0-eddb-4277-86b5-36901851094a",
	"Release": "Dynamic",
	"Include": {
		"Descriptions": true,
		"Translations": true
	}
}

###
# DetailsByFullLocation
POST {{baseUrl}}/api/v1/NlSfb/DetailsByFullLocation HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"Languagecode": "nl-NL",
	"FullLocation": "11.11",
	"Release": "Dynamic"
}

###
# ListByFullLocation
POST {{baseUrl}}/api/v1/NlSfb/ListByFullLocation HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"Languagecode": "nl-NL",
	"FullLocationList": ["11.0", "11.1", "11.11"],
	"Release": "Dynamic"
}