
### variables from .vscode/settings.json

###
# @name ClientCredentialsGrant
POST {{authUrl}}/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{client_id}}
&client_secret={{client_secret}}
&scope=Api


###
# Search
POST {{baseUrl}}/api/v1/Participant/Search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"From": 0,
	"Size": 10,
	"SearchString": "",
	"Filters": [
		{"Code":"ContractCode", "Values": ["300"]}
	]
}

###
# Search with SearchString
POST {{baseUrl}}/api/v1/Participant/Search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"From": 0,
	"Size": 10,
	"SearchString": "test"
}

###
# Search with Filters
POST {{baseUrl}}/api/v1/Participant/Search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"From": 0,
	"Size": 10,
	"SearchString": "",
	"Filters": [
		{"Code":"ParticipantOf", "Values": ["DICO"]},
		{"Code":"BusinessTypes", "Values": ["Bouwbedrijf"]}
	]
}

###
# Search with Filters Certified
POST {{baseUrl}}/api/v1/Participant/Search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"From": 0,
	"Size": 10,
	"OnlySearchCertified": true,
	"SearchString": "",
	"Filters": [
		{"Code":"CertificateStandard", "Values": ["DICO"]},
		{"Code":"CertificateProject", "Values": ["DICO Transactieberichten"]},
		{"Code":"CertificateSpecification", "Values": ["Invoice (Factuur)"]},
		{"Code":"CertificateVersion", "Values": ["005"]}
	]
}

###
# Search with Sorting
POST {{baseUrl}}/api/v1/Participant/Search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"From": 0,
	"Size": 10,
	"SortField": "ParticipantOfDateStart",
	"SortOrder": "Descending",
	"SearchString": "",
	"Filters": [
		{"Code":"ParticipantOf", "Values": ["DICO"]}
	]
}

###
# Search on STABU licenseNumber
POST {{baseUrl}}/api/v1/Participant/Search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"From": 0,
	"Size": 10,
	"SortField": "ParticipantOfDateStart",
	"SortOrder": "Descending",
	"SearchString": "L 19.35.01 E"
}


###
# Aggs
POST {{baseUrl}}/api/v1/Participant/Aggregations HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"SearchString": "",
	"Filters": [
		{"Code":"ParticipantOf", "Values": ["DICO"]},
		{"Code":"BusinessTypes", "Values": ["Bouwbedrijf"]}
		]
}

###
# Aggs
POST {{baseUrl}}/api/v1/Participant/Aggregations HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"OnlySearchCertified": true,
	"SearchString": "",
	"Filters": [
		{"Code":"CertificateSpecification", "Values": ["Invoice (Factuur)"]}
	]
}


###
# Profile
GET {{baseUrl}}/api/v1/Participant/Profile/e689ae0e-dbb3-4c08-a1ef-df3f8f7784c6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

###
# Participant GetBySlug
GET {{baseUrl}}/api/v1/Participant/GetBySlug/bouwfaktor HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

###
# Participant Get
GET {{baseUrl}}/api/v1/Participant/Get/34b00336-56bd-4df0-abe6-b1e86c418483 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

