
### variables from .vscode/settings.json

###
# @name ClientCredentialsGrant
POST {{authUrl}}/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{client_id}}
&client_secret={{client_secret}}
&scope=Api 


###
# Search
POST {{baseUrl}}/Participant/Search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"From": 0,
	"Size": 10,
	"SearchString": ""
}

###
# Search with SearchString
POST {{baseUrl}}/Participant/Search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"From": 0,
	"Size": 10,
	"SearchString": "test"
}

###
# Search with Filters
POST {{baseUrl}}/Participant/Search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"From": 0,
	"Size": 10,
	"SearchString": "",
	"Filters": [
		{"Code":"ParticipantOf", "Values": ["DICO"]},
		{"Code":"BusinessTypes", "Values": ["Bouwbedrijf"]}
	]
}

###
# Search with Sorting
POST {{baseUrl}}/Participant/Search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"From": 0,
	"Size": 10,
	"SortField": "ParticipantOfDateStart",
	"SortOrder": "Descending",
	"SearchString": "",
	"Filters": [
		{"Code":"ParticipantOf", "Values": ["DICO"]}
	]
}

###
# Aggs
POST {{baseUrl}}/Participant/Aggregations HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ClientCredentialsGrant.response.body.$.access_token}}

{
	"SearchString": "",
	"Filters": [
		{"Code":"ParticipantOf", "Values": ["DICO"]},
		{"Code":"BusinessTypes", "Values": ["Bouwbedrijf"]}
		]
}

