
### variables from .vscode/settings.json

//
// Use the following two step process with the authorization code flow
// Replace PKCE code_challenge, code_challenge_method & with your own 
// 

### ACF STEP 1 - after "Send Request" click on the "Location" link in the response window
# @name login
POST {{authUrl}}/connect/Authorize HTTP/2.0
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&response_type=code
&client_id={{client_id}}
&redirect_uri=https://localhost
&scope=openid Api ApiSystematic offline_access
&code_challenge=KsfDpHBIrhteUa9OezXFuhaXsV77POTEl6avU66UDvU
&code_challenge_method=S256

### ACF STEP 2 - Paste the code from the return url in the reponse blow
# @name AuthorizationCode
POST {{authUrl}}/connect/token HTTP/2.0
Content-Type: application/x-www-form-urlencoded; charset=utf-8

grant_type=authorization_code
&client_id={{client_id}}
&client_secret={{client_secret}}
&code_verifier=eyIxIjoyMzgsIjIiOjM1LCIzIjoxMDcsIjQiOjEyMH0
&code=[INSERT_CODE_FROM_RETURNURL]
&redirect_uri=https://localhost
&scope=openid Api ApiSystematic

//
// Use the following only with the client credentials flow //
// 

###
# @name AuthorizationCode
POST {{authUrl}}/connect/token HTTP/2.0
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{client_id}}
&client_secret={{client_secret}}
&scope=Api ApiSystematic

###
# Get version
GET {{baseUrl}}/api/v1/Systematic/GetVersion HTTP/2.0
Content-Type: application/json

###
# Get a collection containing all the urls in a concept
GET {{baseUrl}}/api/v1/Systematic/GetUrlByConceptGuid
?guid=00040fd1-c95e-45c4-b3b5-8733cd07b2b7
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get condept version by guid
GET {{baseUrl}}/api/v1/Systematic/GetAllConceptGroupTypes
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get condept version by guid
GET {{baseUrl}}/api/v1/Systematic/GetConceptByCustomerId
?customerId=6605
&headersOnly=true
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get condept version by guid
GET {{baseUrl}}/api/v1/Systematic/GetConceptLatestversionNoByGuid
?guid=2e172648-df5f-4890-b61f-0b310bdbe826
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get condept version by guid
GET {{baseUrl}}/api/v1/Systematic/GetConceptByDerivedfromGUID
?derivedfromGuid=00408d1f-acd3-4e02-bc95-fe129d457cab
&headersOnly=true
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get all manufacturers by search criteria
POST {{baseUrl}}/api/v1/Systematic/GetManufacturerBySearchcriteriaOnConcept
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

{
    "searchcriteria": ["holonite", "rodeca"],
    "flags": "Contains",
    "searchOnFlags": "all"
}

###
# Get condept version by guid
GET {{baseUrl}}/api/v1/Systematic/GetConceptByGUID
?guid=04b337d6-1c32-4c8f-adfc-a1aaa964f9a8
&headersOnly=true
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get last changed concept
GET {{baseUrl}}/api/v1/Systematic/GetConceptLastChange
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get condept version by guid
GET {{baseUrl}}/api/v1/Systematic/GetConceptByIndexGUID
?guid=4770aa3b-1c18-4fb5-88d4-82e23e8ba557
&headersOnly=false
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get all manufacturers by search criteria
POST {{baseUrl}}/api/v1/Systematic/GetManufacturerBySearchcriteria
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

{
    "searchcriteria": ["bouw", "attema"],
    "flags": "Contains",
    "searchOnFlags": "all"
}

###
# Get last changed index
GET {{baseUrl}}/api/v1/Systematic/GetIndexLastChange
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}


###
# Get all manufacturers
GET {{baseUrl}}/api/v1/Systematic/GetManufacturerAll
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}


###
# Get index categories
GET {{baseUrl}}/api/v1/Systematic/GetIndexCategories
?startIndex=0
&resultsToGet=1000 HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get filtered index categories
GET {{baseUrl}}/api/v1/Systematic/GetIndexCategories
?startIndex=0
&resultsToGet=1000
&requestedElements=7000,7001,7002,7003,7004 HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get index categories
GET {{baseUrl}}/api/v1/Systematic/GetIndexCategoriesByParentId
?parentId=8002
&startIndex=0
&resultsToGet=1000 HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get root indexes
GET {{baseUrl}}/api/v1/Systematic/GetStartingPoints
?startIndex=0
&resultsToGet=1000
&language=en-GB HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get index
GET {{baseUrl}}/api/v1/Systematic/GetIndexByGUID
?guid=c54ed438-7b17-4920-9be4-eb9967b733a6
&language=en-GB HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get child indexes
GET {{baseUrl}}/api/v1/Systematic/GetIndexesByParentGUID
?guid=64071d09-ecea-45e8-b194-9d1c88bcc0c2
&startIndex=0
&resultsToGet=1000
&language=en-GB HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get filtered child indexes
GET {{baseUrl}}/api/v1/Systematic/GetIndexesByParentGUID
?guid=64071d09-ecea-45e8-b194-9d1c88bcc0c2
&startIndex=0
&resultsToGet=1000
&language=en-GB
&requestedElements=7004 HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get parent indexes
GET {{baseUrl}}/api/v1/Systematic/GetIndexesByChildGUID
?guid=0016cc9e-fe7f-444b-bc6c-24de24b3c12f
&startIndex=0
&resultsToGet=1000
&language=en-GB HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get filtered parent indexes
GET {{baseUrl}}/api/v1/Systematic/GetIndexesByChildGUID
?guid=0016cc9e-fe7f-444b-bc6c-24de24b3c12f
&startIndex=0
&resultsToGet=1000
&language=en-GB
&requestedElements=7004 HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Search concepts with groups included in result
POST {{baseUrl}}/api/v1/Systematic/SearchConcepts
?startIndex=0
&resultsToGet=1000
&includeConceptGroups=true HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

{
    "AuthorId": 9,
    "GroupTypeId": 2,
    "VariantTypeId": 38,
    "Status": "published",
    "Name": "Maco*"
}

###
# Search concepts with groups
POST {{baseUrl}}/api/v1/Systematic/SearchConcepts
?startIndex=0
&resultsToGet=1000
&includeConceptGroups=true HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

{
    "Guid": "04b48601-6917-4ef5-8258-d4aa61e4b099"
}

###
# Get customer
GET {{baseUrl}}/api/v1/Systematic/GetCustomerById
?id=5668 HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}


###
# Get manufacturer by concept guid
GET {{baseUrl}}/api/v1/Systematic/GetManufacturerByConceptGUID
?guid=0012f529-4667-4667-9c2b-4a18ece17245 HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}

###
# Get all concept variant types
GET {{baseUrl}}/api/v1/Systematic/GetAllConceptVariantTypes HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{AuthorizationCode.response.body.$.access_token}}